channels:
  - conda-forge
dependencies:
  - appmode
  - pip
  - pip:
    - neuralcoref==4.0
    - pandas==1.3.2
    - pyvis==0.1.9
    - qgrid==1.3.1
    - spacy==2.3.7
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-2.3.1/en_core_web_lg-2.3.1.tar.gz
