channels:
  - conda-forge
dependencies:
  - appmode
  - pip
  - pip:
    - spacy==3.1.2
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0.tar.gz
