channels:
  - conda-forge
dependencies:
  - appmode
  - pip
  - pip:
    - pandas==1.0.5
    - pyvis==0.1.9
    - qgrid==1.3.1
    - spacy==3.1.2
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.1.0/en_core_web_lg-3.1.0.tar.gz
